### PR TITLE
Improve responsiveness

### PR DESCRIPTION
**Pull request by mariuskiessling**
The content (nav, footer and landing page content) now properly align
and resize well on mobile resolutions. In addition, a few absolute
pixel-based sizes were replaced by relative rem-based units.

### CODE REVIEW

**Comment by mariuskiessling** [comment]
@zischknall Please review #6 before this PR. As soon as this review is done, I will rebase this branch on main and open the PR for review.

**Comment by mariuskiessling** [comment]
@zischknall I have rebased the branch. Could you now take a look at the changes?

**Comment by zischknall** [comment]
Is this one still necessary after #8 ?

**Comment by mariuskiessling** [comment]
Ah damn. I accidentally included the commit from this PR in #8. Thus, we can close this. Sorry about that.

**Pull request closed without merging**
